#page title
page_title                                : AnyUpp

# App Info
ios_app_id                                : 1214718958

appstore_link                             : https://apps.apple.com/hu/app/geol%C3%A1d%C3%A1k/id1214718958?l=hu
playstore_link                            : https://play.google.com/store/apps/details?id=com.tamaspetro.geocachinghu&hl=hu
presskit_download_link                    : 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Okos és érintésmentes éttermi rendelés és fizetés

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : CyBERG                                
your_link                                 : https://www.anyupp.com
your_city                                 : Budapest                    
email_address                             : info@cyberg.net
facebook_username                         : 
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Okos éttermi fizetés
    description                           : Rendelj és fizess érintésmentesen az okos alkalmazásunkkal
    fontawesome_icon_name                 : magic
    
  - title                                 : iPhone és Android
    description                           : Töltsd le az alkalmazást és használd az AnyUpp éttermekben
    fontawesome_icon_name                 : mobile

  - title                                 : QR kóddal indul
    description                           : Scanneld be a QR kódot és már rendelhetsz is
    fontawesome_icon_name                 : play-circle

  - title                                 : Folyamatos fejlesztés
    description                           : Sok-sok újdonság várható a következő hónapok folyamán
    fontawesome_icon_name                 : sync

  - title                                 : Kedvencek kezelése
    description                           : Mentsd el kedvenc termékeidet, hogy gyorsan tudd őket rendelni
    fontawesome_icon_name                 : adjust
  
  - title                                 : Szeretnéd máshol használni?
    description                           : Ajánlj minket kedvenc éttermeidnek!
    fontawesome_icon_name                 : star



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"






####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
